on:
  push:
    tags:
      - 'linux_firmware-*'

jobs:
  build:
    name: Build Linux firmware package
    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        # Install makepkg deps
        pacman --noconfirm -Syu
        pacman --noconfirm -S sudo binutils fakeroot base-devel git rdfind 

    - name: Build Package
      run: |
        cd linux-firmware

        # Fix permissions (can't makepkg as root)
        echo "nobody ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers
        chown -R nobody .

        # Package compression settings (Matches latest Arch)
        export PKGEXT='.pkg.tar.zst'
        export COMPRESSZST=(zstd -c -T0 --ultra -20 -)
        export MAKEFLAGS="-j2"

        # Build linux-firmware
        su nobody --pty -p -s /bin/bash -c 'makepkg -f --syncdeps --skippgpcheck --noconfirm'

        # Build linux-firmware-lenovo-sm8250
        cd ../linux-firmware-lenovo-sm8250
        chown -R nobody .
        su nobody --pty -p -s /bin/bash -c 'makepkg -f --syncdeps --skippgpcheck --noconfirm'

    - name: Prepare release
      run: |
        mkdir release
        mv linux-firmware/*.pkg.tar.zst release
        mv linux-firmware-lenovo-sm8250/*.pkg.tar.zst release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-firmware-aarch64-latest
        path: release

  release:
    name: Publish release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-firmware-aarch64-latest
  
    - name: ls artifacts
      run: |
        ls ./

    - name: Upload assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.BUILD_TOKEN }}
        file: ./*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

      
