name: Build kernel deb packages
on:
  push:
    tags:
      - 'debian*'
jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: sudo bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-sdm845-aarch64-latest
          path: ${{ github.workspace }}/artifact/
  release:
    name: Publish release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-sdm845-aarch64-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.BUILD_TOKEN }}
        file: ./*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true